; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[platformio]
; default_envs = ESP8266-nodemcuv2
default_envs = ESP32-dev

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	dfrobot/DFRobot_RGBLCD1602 ;		https://registry.platformio.org/libraries/dfrobot/DFRobot_RGBLCD1602
	mathertel/OneButton ;				https://registry.platformio.org/libraries/mathertel/OneButton
	tobiasschuerg/ESP8266 Influxdb ;	https://registry.platformio.org/libraries/tobiasschuerg/ESP8266%20Influxdb
	adafruit/Adafruit SGP40 Sensor ;	https://registry.platformio.org/libraries/adafruit/Adafruit%20SGP40%20Sensor
	; adafruit/Adafruit SCD30 ;			https://registry.platformio.org/libraries/adafruit/Adafruit%20SCD30
	sparkfun/SparkFun SCD4x Arduino Library ; https://registry.platformio.org/libraries/sparkfun/SparkFun%20SCD4x%20Arduino%20Library
	https://github.com/sparkfun/SparkFun_SCD30_Arduino_Library.git

[env:ESP8266-nodemcuv2]
platform = espressif8266
board = nodemcuv2

[env:ESP32-dev]
platform = espressif32
board = esp32dev
